### ISSUE TITLE
JSON-ify `Teams` with Javascript values

### ISSUE THREAD

**Issue by whroman** [xmunoz/uwrtourist#1]
Python's `None` data type is erroneously being converted to a JS string `"None"`. `undefined` seems like the most-equivalent JS data type to `None`, IMO.

{
    "name": "San Francisco Sea Bass",
    "contacts": [],
    "photo": "None",
    "date_modified": "2015-04-03 17:26:58.894580",
    "blurb": "None",
    "logo": "None",
    "date_created": "2015-04-03 17:26:58.894491",
    "id": "1",
    "practice_times": [],
    "location": "San Francisco, CA, USA",
}

**Comment by xmunoz** [comment]
Looks like this bug might require a bit of hunting, since apparently this is the default behavior of the json python module:

```
>>> import json
>>> json.dumps([1, None, 0, ""])
'[1, null, 0, ""]'
```

**Comment by whroman** [comment]
@xmunoz `null` works for me too!
