### ISSUE TITLE
Remove items in `teams[team].links` that don't have links

### ISSUE THREAD

**Issue by whroman** [xmunoz/uwrtourist#3]
I am going allow the front end to receive `teams[team].links` items that have no valid `link` property and handle them well. However, I think cleaning out the DB by removing said link items would be ideal. 

{
    "date_created": "20:56 07-04-15",
    "team_id": "6",
    "link": "",
    "id": "14",
    "date_modified": "20:56 07-04-15"
}

**Comment by whroman** [comment]
This is a bug. Will do.

**Comment by xmunoz** [comment]
Yes, this is a bug for sure. Will fix now.

**Comment by xmunoz** [comment]
It this still a problem? looks like I fixed it somewhere along the way...

**Comment by whroman** [comment]
@xmunoz I have not seen this anymore.
