### ISSUE TITLE
Finland team updates on prod

### ISSUE THREAD

**Issue by whroman** [xmunoz/uwrtourist#8]
These are teams in Finland that need to have their regions updated
# < Region >

< City >
# Uusimaa

Hyvinkää
Tuusula
Vantaa
# North Karelia

Joensuu
# Central Finland

Jyväskylä
# Western Finland

Kokkola
# Kymenlaakso

Kotka
Kouvola
# Pirkanmaa

Nokia
Tampere
# Northern Ostrobothnia

Oulu
Ylivieska
# Southern Ostrobothnia

Seinäjoki
# Satakunta

Rauma
# Lapland

Tornio
# Izmir UWR Team
- remove current link
- add link: https://www.facebook.com/egeuwr
# UWR PF České Budějovice
- add contacts:
  - uwrugby.b@gmail.com
  - uwrugby.cb@googlegroups.cz
- add links:
  - http://www.uwrugby.com/
  - https://www.facebook.com/pages/Podvodn%C3%AD-ragby-PF-%C4%8Cesk%C3%A9-Bud%C4%9Bjovice/260408986766
- update location: České Budějovice, South Bohemia
- add practice times:
  Tuesday: from 20.00 to 21.30 hours
  Wednesday: from 20.00 to 21.30 hours (Juniors)
  Thursday: from 20.00 to 21.30 hours

**Comment by xmunoz** [comment]
Got rid of the question marks by changing the default encoding of the database and the encoding for each table to `utf8` (was `latin1` for some reason...):

```
ALTER DATABASE uwrtourist DEFAULT CHARACTER SET utf8;
ALTER TABLE teams CONVERT TO CHARACTER SET utf8;
```

I also finished all of the other updates except for adding the new information for UWR PF České Budějovice. I think we should try to do that through the form once we get it working.
